# Copyright (c) Foco Liao. All rights reserved.
author: 'Foco Liao'

original_data_path: #原始数据路径
  image: /home/foco/workspace/DataSets/OriginalData/YOLOv8GP/images/  # for linux
  label: /home/foco/workspace/DataSets/OriginalData/YOLOv8GP/labels/  # for linux
  # image: /Users/foco/Desktop/work/workspace/DataSets/OriginalData/YOLOv8GP/images/    # for mac
  # label: /Users/foco/Desktop/work/workspace/DataSets/OriginalData/YOLOv8GP/labels/    # for mac
destination_data_path:   #目标数据路径
  train:
    image: /home/foco/workspace/DataSets/YOLOv8GP/images/train/  # for linux
    label: /home/foco/workspace/DataSets/YOLOv8GP/labels/train/  # for linux
    # image: /Users/foco/Desktop/work/workspace/DataSets/YOLOv8GP/images/train/    # for mac
    # label: /Users/foco/Desktop/work/workspace/DataSets/YOLOv8GP/labels/train/    # for mac
  val:
    image: /home/foco/workspace/DataSets/YOLOv8GP/images/val/  # for linux
    label: /home/foco/workspace/DataSets/YOLOv8GP/labels/val/  # for linux
    # image: /Users/foco/Desktop/work/workspace/DataSets/YOLOv8GP/images/val/    # for mac
    # label: /Users/foco/Desktop/work/workspace/DataSets/YOLOv8GP/labels/val/    # for mac
  test:
    image: /home/foco/workspace/DataSets/YOLOv8GP/images/test/  # for linux
    # image: /Users/foco/Desktop/work/workspace/DataSets/YOLOv8GP/images/test/    # for mac

image_paths_dir: /home/foco/workspace/DataSets/YOLOv8GP/  # for linux
# image_paths_dir: /Users/foco/Desktop/work/workspace/DataSets/YOLOv8GP/    # for mac
train_image_paths_name: train_image_paths.txt
labels_dir: /home/foco/workspace/DataSets/FocoMonoGP/  # for linux
# labels_dir: /Users/foco/Desktop/work/workspace/DataSets/YOLOv8GP/    # for mac
train_lables_name: train_labels.txt

trainval_percent: 1
train_percent: 0.95
test_percent: 0

image_size_MAXX: 1920   # 原始图片
image_size_MAXY: 1080   # 原始图片
resize_MAXX: 640    # resize图片
resize_MAXY: 640    # resize图片
rect_area_threshold: 0   # 外接框的像素大小阈值 400是个不错的值
image_surfix: '.jpg'