# Copyright (c) Foco Liao. All rights reserved.
author: 'Foco Liao'

train: /home/foco/workspace/DataSets/YOLOv8GP/images/train/
val: /home/foco/workspace/DataSets/YOLOv8GP/images/val/

# Classes

names:
  0: bicycle
  1: car
  2: truck
  3: bus

nc: 4