# Copyright (c) Foco Liao. All rights reserved.
author: 'Foco Liao'

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]

model_yaml: yolov8n.yaml
data_yaml: ../configs/yolov8_gp_data.yaml
save_period: 1


# First train
checkpoint: yolov8n.pt

# Following resume: 

resume_checkpoint: /home/foco/workspace/YOLOv8_GP/YOLOv8_GP/runs/detect/train9/weights/last.pt

new: False