# Copyright (c) Foco Liao. All rights reserved.
author: 'Foco Liao'

train: /home/foco/workspace/DataSets/YOLOv8GP/images/train/   # linux系统中的位置
val: /home/foco/workspace/DataSets/YOLOv8GP/images/val/       # linux系统中的位置

# train: /Users/foco/Desktop/work/workspace/DataSets/YOLOv8GP/images/train/     # Mac中的位置
# val: /Users/foco/Desktop/work/workspace/DataSets/YOLOv8GP/images/val/         # Mac中的位置

# Classes

names:
  0: car
  1: bus
  2: truck
  3: bicycle

nc: 4